### ISSUE TITLE
Any chance to support TypeScript/increase robustness against syntax errors?

### ISSUE THREAD

**Issue by LinqLover** [TomerAberbach/parse-imports#1]
At the moment, I'm getting a large number of parse errors from lexer when parsing `.ts` files because, obviously, TypeScript is a superset of plain JavaScript. Nevertheless, import statements are not very complex - the only difference I'm aware of is TypeScript's `import … =` statement. But also apart from JavaScript, the import parser breaks completely if there any missing comma or something like this at the end of a file. Would it be in the scope of this package to increase robustness, and maybe even to support TypeScript imports? Thanks in advance!

**Comment by TomerAberbach** [comment]
Hey! Thanks for the issue.

This package is basically a wrapper around [`es-module-lexer`](https://github.com/guybedford/es-module-lexer). `es-module-lexer` identifies the character ranges that correspond to import statements and expressions, and then this package parses specifiers and other information from each character range.

So based on that I think your feature request would fall into `es-module-lexer`'s domain and I would recommend filing an issue there.

Alternatively, at least for the TypeScript case, you could transpile the code to JavaScript before passing it to `parse-imports`. Sorry I couldn't be of more help!

**Comment by LinqLover** [comment]
Thank you for the feedback. Transpiling was an important hint. In my scenario, I am now using the `typescript` package to run even more detailed analysis on the source code.
