### ISSUE TITLE
Sync method

### ISSUE THREAD

**Issue by brettz9** [TomerAberbach/parse-imports#10]
Hi,

I'm working with `eslint-plugin-jsdoc` and we have a need for parsing import statements (for use within `@import` tags). However, ESLint does not allow asynchronous rules.

I know that `es-module-lexer` mentions using async to be safe, but when I tested it within eslint, it seems enough time has passed for Wasm to load such that I could successfully get results using its `parse` method synchronously.

I am wondering if you could expose a sync version of `parseImports` (that presupposes it is called with enough time for Wasm to load)?

**Comment by TomerAberbach** [comment]
What you observed does make sense given that the WASM apparently takes only [5ms to boot](https://github.com/guybedford/es-module-lexer#wasm-build)!

I think a `parseImportsSync` method could make sense. Maybe I would also expose an `wasmBootPromise` that people can await if they want (even if you personally wouldn't be depending on that). Will probably be able to get to this soon. Thanks for filing :)

**Comment by TomerAberbach** [comment]
One thing I will mention is that jsdoc isn't valid JavaScript if you consider only the content within the comment and exclude the comment delimiters. I do wonder whether `es-module-lexer` always parses jsdoc imports correctly (given that there's an `@` before `import`). I'll assume you've already looked into that

**Comment by brettz9** [comment]
That's right, I'd be supplying my own well-formed import statements based on the comments content, but not including the `@`. (TS suggests these comments are otherwise just well-formed imports.)

**Comment by TomerAberbach** [comment]
Got it. Makes sense!

**Comment by TomerAberbach** [comment]
@brettz9 are you able to confirm whether #11 does what you need?

Will need to be breaking change since I'm swapping the async method from a default import to a named import

**Comment by brettz9** [comment]
LGTM, thanks!

**Comment by TomerAberbach** [comment]
Published in v2.0.0!

**Comment by brettz9** [comment]
Awesome, appears to be working great too, thanks!

**Comment by TomerAberbach** [comment]
No problem! Glad it's working 😁
